/**
 * Generate BOC-style practice questions for targeted PA8 domains and insert them
 * into the `questions` table. Built to top up the domains a prior attempt scored
 * weakest in — by default D2 (Assessment, Evaluation & Diagnosis) and D3
 * (Critical Incident Management), with a heavy share of multi-select ("select
 * all that apply") items because that is the format that costs the most points.
 *
 * Each question is generated by Claude grounded in the official PA8 blueprint and
 * the chosen domain's task statements, returned as strict JSON, then inserted
 * tagged to its domain + task. Questions are marked sourceKind="ai" and
 * pendingReview=true so they are clearly distinguishable from the real imported
 * bank and can be spot-checked — they are AI-generated and should be reviewed for
 * clinical accuracy before you rely on them.
 *
 * Idempotent-ish: skips any generated stem that collides with an existing one.
 *
 * Usage:
 *   pnpm --filter @workspace/scripts exec tsx ./src/generateQuestions.ts [flags]
 *
 *   --domain D2          domain to target (repeatable; default: D2 and D3)
 *   --count N            questions per domain (default 40)
 *   --batch N            questions per generation call (default 8)
 *   --concurrency N      generation calls in parallel (default 3)
 *   --multi-pct N        approx. % that should be multi-select (default 60)
 *   --dry-run            generate + report, write nothing
 *
 * Requires: DATABASE_URL, AI_INTEGRATIONS_ANTHROPIC_* env vars.
 */
import { db, domains, tasks, topics, questions } from "@workspace/db";
import { anthropic } from "@workspace/integrations-anthropic-ai";

const MODEL = "claude-opus-4-8"; // generation quality matters more here than in classification
const MAX_TOKENS = 8_000;

const DOMAIN_NAMES: Record<string, string> = {
  D1: "Risk Reduction, Wellness & Health Literacy",
  D2: "Assessment, Evaluation & Diagnosis",
  D3: "Critical Incident Management",
  D4: "Therapeutic Intervention",
  D5: "Healthcare Administration & Professional Responsibility",
};

const TASKS_BY_DOMAIN: Record<string, string> = {
  D1: "0101 identify risk factors/screening; 0102 risk-reduction plans; 0103 health literacy/education; 0104 optimize wellness; 0105 environmental safety (heat/cold/lightning/surfaces)",
  D2: "0201 history/interview; 0202 physical exam/special tests; 0203 formulate clinical diagnosis; 0204 establish plan of care; 0205 educate on diagnosis/prognosis",
  D3: "0301 Emergency Action Plans; 0302 triage severity; 0303 emergent care (CPR/AED/c-spine/airway/heat stroke/anaphylaxis/hemorrhage/spinal); 0304 assess the scene",
  D4: "0401 develop/update plan of care; 0402 educate during intervention; 0403 prescribe therapeutic exercise; 0404 modalities/devices; 0405 manual therapy; 0406 functional status/return-to-play; 0407 manage general medical conditions/pharmacology",
  D5: "0501 quality-improvement/outcomes; 0502 policies & procedures; 0503 laws/standards (HIPAA/FERPA/scope/ethics); 0504 documentation/SOAP",
};

type Args = { domainCodes: string[]; count: number; batch: number; concurrency: number; multiPct: number; dryRun: boolean };

function parseArgs(argv: string[]): Args {
  const args: Args = { domainCodes: [], count: 40, batch: 8, concurrency: 3, multiPct: 60, dryRun: false };
  const rest = argv.slice(2);
  for (let i = 0; i < rest.length; i += 1) {
    const a = rest[i];
    if (a === "--") continue;
    else if (a === "--dry-run") args.dryRun = true;
    else if (a === "--domain") { const c = (rest[++i] ?? "").toUpperCase(); if (DOMAIN_NAMES[c]) args.domainCodes.push(c); }
    else if (a === "--count") args.count = Math.max(1, Number(rest[++i]) || 40);
    else if (a === "--batch") args.batch = Math.max(1, Number(rest[++i]) || 8);
    else if (a === "--concurrency") args.concurrency = Math.max(1, Number(rest[++i]) || 3);
    else if (a === "--multi-pct") args.multiPct = Math.min(100, Math.max(0, Number(rest[++i]) || 60));
    else throw new Error(`Unknown flag: ${a}`);
  }
  if (args.domainCodes.length === 0) args.domainCodes = ["D2", "D3"];
  return args;
}

const normalize = (s: string) => s.toLowerCase().replace(/\s+/g, " ").trim();

type GenQuestion = {
  stem: string;
  choices: string[];
  correctIndices: number[];
  multiSelect: boolean;
  rationale: string;
  task: string;
  difficulty: number;
};

async function generateBatch(domainCode: string, n: number, multiPct: number, avoid: string[]): Promise<GenQuestion[]> {
  const prompt = `Write ${n} board-exam practice questions for the BOC (Board of Certification for Athletic Trainers) entry-level exam, PA8 blueprint.

TARGET DOMAIN ${domainCode}: ${DOMAIN_NAMES[domainCode]}
TASKS (use the "task" field to tag each question to the most relevant one):
${TASKS_BY_DOMAIN[domainCode]}

REQUIREMENTS:
- About ${multiPct}% of the questions must be multi-select ("Select all that apply") with 2–4 correct options; the rest single-answer.
- 4–6 plausible answer choices each; distractors must be genuinely tempting, not obviously wrong.
- Clinically accurate and consistent with current athletic-training standards of care (NATA position statements, current ECC/CPR, CISG concussion consensus). Realistic clinical scenarios where appropriate.
- Each needs a concise rationale explaining why the correct option(s) are right AND why key distractors are wrong.
- Mix difficulty: ~recall, ~application, ~analysis.
- Do NOT duplicate these existing stems: ${avoid.slice(0, 40).map((s) => `"${s.slice(0, 70)}"`).join("; ")}

WRITE IN OFFICIAL BOC EXAM-DEVELOPMENT STYLE (these are graded):
- Every stem is a complete QUESTION ending in "?". No statements, completions, or fill-in-the-blank stems.
- Third person, person-first: "An athletic trainer…", "A patient with a sprained ankle…". Never "you/your".
- State items POSITIVELY. Never use "EXCEPT", "NOT", "all of the following", or "least likely" — ask the positive form (e.g. "Which are contraindications for…?").
- Test ONE concept per item (do not ask to identify a condition AND the next step in the same item).
- No "all of the above", "none of the above", "a and b", or "I don't know" options. No absurd/implausible distractors.
- Distractors must be the same family as the answer (all muscles, all tests, all conditions…) and of similar length — no long-correct-answer cue.
- Use they/them/their unless the item clinically requires a sex; use "erythema/pallor", not "redness".
- Terminology: "athletic trainer" (not "certified athletic trainer"), "physician" (not "doctor"), "athletic training facility" (not "room"). Refer to medications by action ("NSAID", "antibiotic"), never brand names.
- When the answer is the single best option, phrase the stem with "best" or "most" so one option is clearly optimal.
- Numbers <10 spelled out; leading zero on decimals (0.5); spinal segments with no hyphen (C4); customary units with metric in parentheses (160 lbs (72.5 kg); 104 degrees F (40 degrees C)).
- Entry-level, evidence-based content (double-referenceable) — no obscure trivia or textbook-verbatim recall.

Return ONLY JSON: {"questions":[{"stem":"...","choices":["...","..."],"correctIndices":[0,2],"multiSelect":true,"rationale":"...","task":"0202","difficulty":2}]}. correctIndices are 0-based into choices. For single-answer items, multiSelect=false and correctIndices has exactly one element.`;

  const message = await anthropic.messages.create({
    model: MODEL,
    max_tokens: MAX_TOKENS,
    system: "You are a certified athletic trainer and BOC item writer. You write accurate, exam-realistic questions and respond with valid JSON only.",
    messages: [{ role: "user", content: prompt }],
  });
  const text = message.content.map((b) => (b.type === "text" ? b.text : "")).join("");
  const json = text.slice(text.indexOf("{"), text.lastIndexOf("}") + 1);
  const parsed = JSON.parse(json) as { questions?: GenQuestion[] };
  return parsed.questions ?? [];
}

async function pool<T, R>(items: T[], limit: number, fn: (item: T, index: number) => Promise<R>): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let next = 0;
  async function worker() {
    while (next < items.length) {
      const i = next++;
      results[i] = await fn(items[i], i);
    }
  }
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
  return results;
}

/** Validate a generated question and coerce to an insertable row, or null. */
function toRow(
  g: GenQuestion,
  domainId: number,
  taskIdByCode: Map<string, number>,
  topicIdForDomain: number | null,
  seen: Set<string>,
) {
  if (!g.stem || !Array.isArray(g.choices) || g.choices.length < 2) return null;
  if (!Array.isArray(g.correctIndices) || g.correctIndices.length === 0) return null;
  const correct = [...new Set(g.correctIndices)].sort((a, b) => a - b);
  if (correct.some((i) => !Number.isInteger(i) || i < 0 || i >= g.choices.length)) return null;
  const key = normalize(g.stem);
  if (seen.has(key)) return null;
  seen.add(key);
  const multiSelect = !!g.multiSelect || correct.length > 1;
  return {
    stem: g.stem.trim(),
    choices: g.choices,
    correctIndex: correct[0],
    multiSelect,
    correctIndices: multiSelect ? correct : null,
    rationale: g.rationale?.trim() || "AI-generated; rationale pending review.",
    domainId,
    topicId: topicIdForDomain,
    taskId: taskIdByCode.get(g.task) ?? null,
    difficulty: [1, 2, 3].includes(g.difficulty) ? g.difficulty : 2,
    sourceKind: "ai",
    enabled: true,
    pendingReview: true, // AI-generated — flagged for clinical spot-check
  };
}

async function main() {
  const args = parseArgs(process.argv);
  console.log(
    `Generating ${args.count} q/domain for [${args.domainCodes.join(", ")}] ` +
      `(~${args.multiPct}% multi-select)${args.dryRun ? " [dry-run]" : ""}`,
  );

  const [dRows, taskRows, topicRows, existing] = await Promise.all([
    db.select().from(domains),
    db.select().from(tasks),
    db.select().from(topics),
    db.select({ stem: questions.stem }).from(questions),
  ]);
  const domainIdByCode = new Map(dRows.map((d) => [d.code, d.id]));
  const taskIdByCode = new Map(taskRows.map((t) => [t.code, t.id]));
  // A representative topic per domain to tag generated questions (optional).
  const topicForDomainId = new Map<number, number>();
  for (const t of topicRows) if (!topicForDomainId.has(t.domainId)) topicForDomainId.set(t.domainId, t.id);
  const seen = new Set(existing.map((q) => normalize(q.stem)));
  if (dRows.length === 0) throw new Error("No domains seeded — run the seed script first.");

  const allRows: ReturnType<typeof toRow>[] = [];
  for (const code of args.domainCodes) {
    const domainId = domainIdByCode.get(code);
    if (domainId == null) { console.warn(`  ${code} not seeded — skipping`); continue; }
    const batches: number[] = [];
    for (let remaining = args.count; remaining > 0; remaining -= args.batch) batches.push(Math.min(args.batch, remaining));

    const avoid = [...seen].slice(-60);
    const generated = (
      await pool(batches, args.concurrency, async (nBatch, bi) => {
        try {
          return await generateBatch(code, nBatch, args.multiPct, avoid);
        } catch (err) {
          console.error(`  ${code} batch ${bi + 1} failed: ${(err as Error).message}`);
          return [] as GenQuestion[];
        }
      })
    ).flat();

    let kept = 0;
    for (const g of generated) {
      const row = toRow(g, domainId, taskIdByCode, topicForDomainId.get(domainId) ?? null, seen);
      if (row) { allRows.push(row); kept += 1; }
    }
    const ms = generated.filter((g) => g.multiSelect || (g.correctIndices?.length ?? 0) > 1).length;
    console.log(`  ${code}: generated ${generated.length}, kept ${kept} (${ms} multi-select)`);
  }

  const rows = allRows.filter((r): r is NonNullable<typeof r> => r != null);
  console.log(`Total new questions: ${rows.length}`);
  if (args.dryRun) {
    console.log("[dry-run] no rows written. Sample:");
    for (const r of rows.slice(0, 3)) console.log(`  • ${r.stem.slice(0, 90)}${r.multiSelect ? " [multi]" : ""}`);
    return;
  }
  for (let i = 0; i < rows.length; i += 100) await db.insert(questions).values(rows.slice(i, i + 100));
  console.log(`Inserted ${rows.length} AI-generated questions (flagged pendingReview).`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
