uploads = []

[[generated]]
id = "LyOft6DwXq-5CwuWl_CqF"
uri = "file://artifacts/boc-notebook/src/assets/anatomy/layer-skin.png"
type = "image"
title = "anatomy skin layer"

[[generated]]
id = "iXLlE19JnMZUeBwv-moS5"
uri = "file://artifacts/boc-notebook/src/assets/anatomy/layer-muscle.png"
type = "image"
title = "anatomy muscle layer"

[[generated]]
id = "uuRUPzdCLXb3dSpKBUDuz"
uri = "file://artifacts/boc-notebook/src/assets/anatomy/layer-skeleton.png"
type = "image"
title = "anatomy skeleton layer"

[[generated]]
id = "_kmq4X-x8u3CVgRmzQW1D"
uri = "file://artifacts/boc-notebook/src/assets/anatomy/layer-skin-back.png"
type = "image"
title = "posterior skin layer registered"

[[generated]]
id = "G2JceVcdvHFAOxZ5Zc7ME"
uri = "file://artifacts/boc-notebook/src/assets/anatomy/layer-muscle-back.png"
type = "image"
title = "posterior muscle layer registered"

[[generated]]
id = "uRCnqWS_WmaRhwvBseojc"
uri = "file://artifacts/boc-notebook/src/assets/anatomy/layer-skeleton-back.png"
type = "image"
title = "posterior skeleton layer registered"

[[outputs]]
id = "Pi35Bh-xa5NqApXmAmapf"
uri = "file://README.md"
type = "text"
title = "README.md"
