import { Router, type IRouter } from "express";
import healthRouter from "./health";
import catalogRouter from "./catalog";
import blueprintRouter from "./blueprint";
import notebooksRouter from "./notebooks";
import notesRouter from "./notes";
import flashcardsRouter from "./flashcards";
import studyGuidesRouter from "./studyGuides";
import audioOverviewsRouter from "./audioOverviews";
import quizzesRouter from "./quizzes";
import mockExamsRouter from "./mockExams";
import openaiRouter from "./openai";
import dashboardRouter from "./dashboard";
import planRouter from "./plan";
import fixItPlanRouter from "./fixItPlan";
import gameSessionsRouter from "./gameSessions";
import planCompletionsRouter from "./planCompletions";
import topicPodcastsRouter from "./topicPodcasts";
import ttsRouter from "./tts";
import studyGroupRouter from "./studyGroup";
import aiLearningRouter from "./aiLearning";

const router: IRouter = Router();

router.use(healthRouter);
router.use(catalogRouter);
router.use(blueprintRouter);
router.use(notebooksRouter);
router.use(notesRouter);
router.use(flashcardsRouter);
router.use(studyGuidesRouter);
router.use(audioOverviewsRouter);
router.use(quizzesRouter);
router.use(mockExamsRouter);
router.use(openaiRouter);
router.use(dashboardRouter);
router.use(planRouter);
router.use(fixItPlanRouter);
router.use(gameSessionsRouter);
router.use(planCompletionsRouter);
router.use(topicPodcastsRouter);
router.use(ttsRouter);
router.use(studyGroupRouter);
router.use(aiLearningRouter);

export default router;
